// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/30/2024, 11:47:04 PM
const configMerger = require("/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/plugins/**/*.{js,ts,mjs}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/stores/**/*.{js,ts,mjs}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/composables/**/*.{js,ts,mjs}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/utils/**/*.{js,ts,mjs}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/letiendat/Workspace/DEV/PersonalProject/Website/TwitterClone-Nuxt3/src/app.config.{js,ts,mjs}"] }));

module.exports = config
